package bdss.view;

import processing.core.PApplet;
import de.fhpotsdam.unfolding.UnfoldingMap;
import de.fhpotsdam.unfolding.providers.OpenStreetMap.OpenStreetMapProvider;
import de.fhpotsdam.unfolding.utils.MapUtils;
import g4p_controls.*;

public class TrajdbGUI extends PApplet {
	UnfoldingMap map;

	// Serial ID is optional and added by Eclipse
	public void setup() {
		size(1200, 660, P3D);
		if (frame != null) {
			frame.setResizable(true);
		}
		createGUI();
		customGUI();
		// Place your setup code here

	}

	public void draw() {
		background(230);
		map.draw();
	}
	
	public static void main(String args[]) {
		PApplet.main(new String[] { TrajdbGUI.class.getName() });
	}

	// Use this method to add additional statements
	// to customise the GUI controls
	public void customGUI() {
		map = new UnfoldingMap(this, 240, 40, 720, 520, new OpenStreetMapProvider());
		MapUtils.createDefaultEventDispatcher(this, map);
	}

	/* =========================================================
	 * ====                   WARNING                        ===
	 * =========================================================
	 * The code in this tab has been generated from the GUI form
	 * designer and care should be taken when editing this file.
	 * Only add/edit code inside the event handlers i.e. only
	 * use lines between the matching comment tags. e.g.

	 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
	     // It is safe to enter your event code here  
	 } //_CODE_:button1:12356:
	 
	 * Do not rename this tab!
	 * =========================================================
	 */

	public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:941412:
	  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
	} //_CODE_:textfield1:941412:

	public void button1_click1(GButton source, GEvent event) { //_CODE_:loadButton:288552:
	  println("loadButton - GButton >> GEvent." + event + " @ " + millis());
	} //_CODE_:loadButton:288552:

	public void button2_click1(GButton source, GEvent event) { //_CODE_:clearButton:472670:
	  println("clearButton - GButton >> GEvent." + event + " @ " + millis());
	} //_CODE_:clearButton:472670:

	public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:taxiList:640156:
	  println("taxiList - GDropList >> GEvent." + event + " @ " + millis());
	} //_CODE_:taxiList:640156:

	public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:294212:
	  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
	} //_CODE_:textfield2:294212:

	public void textfield3_change1(GTextField source, GEvent event) { //_CODE_:textfield3:354994:
	  println("textfield3 - GTextField >> GEvent." + event + " @ " + millis());
	} //_CODE_:textfield3:354994:

	public void button1_click2(GButton source, GEvent event) { //_CODE_:button1:662089:
	  println("button1 - GButton >> GEvent." + event + " @ " + millis());
	} //_CODE_:button1:662089:

	public void button2_click2(GButton source, GEvent event) { //_CODE_:button2:563953:
	  println("button2 - GButton >> GEvent." + event + " @ " + millis());
	} //_CODE_:button2:563953:

	public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:624658:
	  println("button3 - GButton >> GEvent." + event + " @ " + millis());
	} //_CODE_:button3:624658:

	public void textfield4_change1(GTextField source, GEvent event) { //_CODE_:textfield4:277840:
	  println("textfield4 - GTextField >> GEvent." + event + " @ " + millis());
	} //_CODE_:textfield4:277840:

	public void textfield5_change1(GTextField source, GEvent event) { //_CODE_:textfield5:723072:
	  println("textfield5 - GTextField >> GEvent." + event + " @ " + millis());
	} //_CODE_:textfield5:723072:

	public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:818899:
	  println("button4 - GButton >> GEvent." + event + " @ " + millis());
	} //_CODE_:button4:818899:



	// Create all the GUI controls. 
	// autogenerated do not edit
	public void createGUI(){
	  G4P.messagesEnabled(false);
	  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
	  G4P.setCursor(ARROW);
//	  surface.setTitle("Sketch Window");
	  fileLabel = new GLabel(this, 29, 30, 80, 20);
	  fileLabel.setText("GPS Record");
	  fileLabel.setOpaque(false);
	  textfield1 = new GTextField(this, 128, 27, 224, 30, G4P.SCROLLBARS_NONE);
	  textfield1.setOpaque(true);
	  textfield1.addEventHandler(this, "textfield1_change1");
	  loadButton = new GButton(this, 373, 26, 80, 30);
	  loadButton.setText("Load");
	  loadButton.addEventHandler(this, "button1_click1");
	  clearButton = new GButton(this, 465, 26, 80, 30);
	  clearButton.setText("Clear");
	  clearButton.addEventHandler(this, "button2_click1");
	  label1 = new GLabel(this, 605, 86, 80, 20);
	  label1.setText("Path Query");
	  label1.setOpaque(false);
//	  taxiList = new GDropList(this, 714, 126, 90, 80, 3);
//	  taxiList.setItems(loadStrings("list_640156"), 0);
//	  taxiList.addEventHandler(this, "dropList1_click1");
	  label2 = new GLabel(this, 606, 126, 80, 20);
	  label2.setText("Taxi Id");
	  label2.setOpaque(false);
	  label3 = new GLabel(this, 607, 166, 80, 20);
	  label3.setText("Start Date");
	  label3.setOpaque(false);
	  label4 = new GLabel(this, 605, 212, 80, 20);
	  label4.setText("End Date");
	  label4.setOpaque(false);
	  textfield2 = new GTextField(this, 713, 162, 160, 30, G4P.SCROLLBARS_NONE);
	  textfield2.setOpaque(true);
	  textfield2.addEventHandler(this, "textfield2_change1");
	  textfield3 = new GTextField(this, 714, 206, 160, 30, G4P.SCROLLBARS_NONE);
	  textfield3.setOpaque(true);
	  textfield3.addEventHandler(this, "textfield3_change1");
	  button1 = new GButton(this, 795, 258, 80, 30);
	  button1.setText("Search");
	  button1.addEventHandler(this, "button1_click2");
	  label5 = new GLabel(this, 601, 317, 127, 24);
	  label5.setText("Spatio-Temporal Query");
	  label5.setOpaque(false);
	  button2 = new GButton(this, 603, 359, 80, 30);
	  button2.setText("Region");
	  button2.addEventHandler(this, "button2_click2");
	  button3 = new GButton(this, 708, 360, 80, 30);
	  button3.setText("Clear");
	  button3.addEventHandler(this, "button3_click1");
	  label6 = new GLabel(this, 604, 415, 80, 20);
	  label6.setText("Start Date");
	  label6.setOpaque(false);
	  textfield4 = new GTextField(this, 710, 411, 160, 30, G4P.SCROLLBARS_NONE);
	  textfield4.setOpaque(true);
	  textfield4.addEventHandler(this, "textfield4_change1");
	  label7 = new GLabel(this, 603, 462, 80, 20);
	  label7.setText("End Date");
	  label7.setOpaque(false);
	  textfield5 = new GTextField(this, 710, 458, 160, 30, G4P.SCROLLBARS_NONE);
	  textfield5.setOpaque(true);
	  textfield5.addEventHandler(this, "textfield5_change1");
	  button4 = new GButton(this, 792, 504, 80, 30);
	  button4.setText("Search");
	  button4.addEventHandler(this, "button4_click1");
	}

	// Variable declarations 
	// autogenerated do not edit
	GLabel fileLabel; 
	GTextField textfield1; 
	GButton loadButton; 
	GButton clearButton; 
	GLabel label1; 
	GDropList taxiList; 
	GLabel label2; 
	GLabel label3; 
	GLabel label4; 
	GTextField textfield2; 
	GTextField textfield3; 
	GButton button1; 
	GLabel label5; 
	GButton button2; 
	GButton button3; 
	GLabel label6; 
	GTextField textfield4; 
	GLabel label7; 
	GTextField textfield5; 
	GButton button4; 


}